version: '3'
services:
  inbox:
    ports:
    - "5000:5000"
    image: "enirkesto/inbox"
    links:
    - textanalytics
    - redis
    - mongodb
    
  textanalytics:
    ports:
    image: "enirkesto/textanalytics"

  redis:
    image: "redis"

  mongodb:
    image: "mongo"